### ISSUE TITLE
Suggestion: `setCentAmount()`

### ISSUE THREAD

**Issue by ThomasLandauer** [smhg/sepa-qr-php#10]
What about adding a convenience method called `setCentAmount()`? Reason: When your entire app works with cents (i.e. `int`), it would be nice to just pass this value here, and have the library do the conversion.

**Comment by smhg** [comment]
@ThomasLandauer thanks for the idea. I think however we should stick as close to the EPC spec as possible without offering too much on top. I think that's the main goal of this library.
It's fairly easy to add this conversion to your project and/or to create something on top of `sepa-qr-php` which offers more convenience for specific use-cases.

**Comment by ThomasLandauer** [comment]
Well, we would still stick to the spec, even if we added a handy one-liner that just returns `$centAmount / 100` ;-)

**Comment by smhg** [comment]
What I meant with sticking to the spec: having a one-on-one match between spec properties and methods. There is no `CentAmount` property in the spec, only `Amount`.

It's also super clear to do something like `class MySepaQr extends SepaQr` in your project. Where you add your utility methods. I do that myself.
