### ISSUE TITLE
Background-Color (endroid/qr-code)

### ISSUE THREAD

**Issue by frantischek** [smhg/sepa-qr-php#13]
Hi,
I read that you have all the functionality from endroid/qr-code, but how can I use them? I want to change the color (or background color) of the barcode.
Thanks for help

**Comment by smhg** [comment]
The PHP language allows to extend classes. This is what SepaQr does:
```php
class SepaQr extends QrCode
```
This means you can use all public methods QrCode offers on an instance of SepaQr.
