### ISSUE TITLE
this is more a question than an issue

### ISSUE THREAD

**Issue by netengine-at** [smhg/sepa-qr-php#14]
hi,

since **sepa-qr-php** extends **endroid/qr-code** should it not be possible to call setMargin? when I try this, I get the following error: Call to a member function setMargin() on null

any help would be appreciated!

thanks in advance!

**Comment by smhg** [comment]
As the error message says: the variable you're calling `setMargin` on is empty.

My guess: you're probably chaining to an endroid/qr-code setter method that doesn't return anything.
You can't, for instance, call `$sepaQr->setSize()->setMargin()`. You'll have to do `$sepaQr->setSize()` and `$sepaQr->setMargin()`.
