### ISSUE TITLE
Add support for endroid/qr-code 4.0

### ISSUE THREAD

**Issue by markwatney2016** [smhg/sepa-qr-php#15]
https://github.com/endroid/qr-code/releases

**Comment by smhg** [comment]
`endroid/qr-code` now declares their class as final so we can no longer extend it. What would be the least intrusive way to handle this?
@markwatney2016 any help would be appreciated.

**Comment by markwatney2016** [comment]
@smhg That's a bummer. Would composition (instead of inheritence) be an option for your package?

**Comment by smhg** [comment]
@markwatney2016 I have no preference, whatever works well. What is crucial is that upgrading is the least amount of effort for users of this package.

**Comment by smhg** [comment]
@romainnorberg based on your previous contribution, your input would be very much appreciated.

**Comment by ThomasLandauer** [comment]
Well, instead of extending endroid's `QrCode`, why don't you just `use` it and then instantiate it with `$builder = Builder::create()`, like  ccharz/laravel-epc-qr does it: https://github.com/ccharz/laravel-epc-qr/blob/master/src/LaravelEpcQr.php#L338

**Comment by smhg** [comment]
@ThomasLandauer but then we'd need to add methods for all (useful) QrCode features (size, margin, error correction,...)? 

It sounds better to expose the builder instance. Something like:
```php
$sepaQr = new SepaQr();
$sepaQr->setName('Name of the beneficiary')
  ->setIban('BE123456789123456789')
  ->setAmount(100)
  ->setRemittanceText('Invoice 123456789');
$builder = $sepaQr->getBuilder();
$result = $builder->writer(new PngWriter())
  ->size(300)
  ->build();
```

Or, alternatively, passing it to the constructor? Is that a thing in PHP?
```php
$builder = Builder::create()
    ->writer(new PngWriter())
    ->size(300);
$sepaQr = new SepaQr($builder);
$sepaQr->setName('Name of the beneficiary')
  ->setIban('BE123456789123456789')
  ->setAmount(100)
  ->setRemittanceText('Invoice 123456789');
$result = $sepaQr->build(); // calls $qr->build();
```

The second approach has the advantage defaults only need to be set if no custom builder instance is provided.

Or, we can switch to only data (text) generation:
```php
$sepaData = new SepaQr(); // better class name would be nice
$sepaData->setName('Name of the beneficiary');
// $sepaData->...

$builder = Builder::create($sepaData); // calling $sepaData->toString();
/// $builder->...
$result = $builder->build();
```
It would however require to always set ErrorCorrection to Medium on the builder (as this is a requirement of the standard?). The default is Low.

Although I think the last approach sounds best, it would require much more changes when upgrading. The blame for that, however, is largely on endroid/qr-code...

Any other approaches?

**Comment by ThomasLandauer** [comment]
Sorry, I don't know :-(
Maybe you could ask endroid, what he'd recommend, and why he changed it in the first place...

**Comment by smhg** [comment]
I've gone for the last approach I mentioned. This project lives on in [smhg/sepa-qr-data](https://github.com/smhg/sepa-qr-data-php).

Follow [these steps](https://github.com/smhg/sepa-qr-data-php#migration-from-smhgsepa-qr) to migrate.
