### ISSUE TITLE
Supporting CHF currency

### ISSUE THREAD

**Issue by Jul000** [smhg/sepa-qr-php#16]
Dear,

I would like to know if this project support the CHF currency from switzerland ? if not, if you are projecting to add currencies' update ?

thank a lot 

Julien

**Comment by smhg** [comment]
While I couldn't immediately find a document that explains support for currencies other than EUR (please add a link if you have one), support seems simple.

I've added an attempt to the v3 branch (as support for php8 is in progress for v4). Can I ask you to try it out?
```bash
composer require smhg/sepa-qr:v3.x-dev
```
Afterwards you can add `->setCurrency('CHF')`. Everything else should work the same.

**Comment by smhg** [comment]
@Julien0510 where you able to test this? Happy to release a new version if it's doing the job.

**Comment by ThomasLandauer** [comment]
Here's a generator: https://www.postfinance.ch/de/support/tools-rechner/qr-generator.html
It looks like in Switzerland they're using a different format (text), that starts with "SPC" (instead of "BCD"), but I haven't really researched this...

**Comment by smhg** [comment]
@ThomasLandauer it would be great if you could point us to a spec document for Swiss QR's. Something similar to the [EPC spec](https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2018-05/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf).

**Comment by ThomasLandauer** [comment]
Sorry, I don't know (I'm not even from Switzerland ;-) - maybe @Julien0510 ?

**Comment by smhg** [comment]
I'm closing this issue as this project now lives on in [smhg/sepa-qr-data](https://github.com/smhg/sepa-qr-data-php) (see #15). Please open a new issue with the additional information in that repository.
