### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by fafayqa** [smhg/sepa-qr-php#17]
How can this be installed MANUALLY, that is not using `composer`?
I am using simple USBWebserver for testserer and I am looking for manual way of installation. As it uses still old PHP v5.4.17 I am talking about the version v2.3.0 which was the last one compatible with PHP v5.6.

**Comment by smhg** [comment]
https://stackoverflow.com/questions/40545795/how-do-i-install-composer-php-packages-without-composer will help you.
