### ISSUE TITLE
Remittance reference or text row missing

### ISSUE THREAD

**Issue by mstadius** [smhg/sepa-qr-php#5]
Thank you for the QR code generator! It is working well for me except for one small bug.

As you can see in the examples in the standard document you have linked to in README.md both AT-05 (Remittance text and reference) should always be included even if only one of them will have content.

https://github.com/smhg/sepa-qr-php/blob/116ba2a8f4c21c024e0eb6d2e02361c51308aeda/src/SepaQr/SepaQr.php#L217

There seems to exist a fork that has this issue fixed.

https://github.com/makuser/sepa-qr-php/blob/master/src/SepaQr/SepaQr.php#L208

I have tested with Nordeas mobile app to verify that both lines should always be included.

**Comment by smhg** [comment]
Please correct me if I'm wrong, but I read _page 2_ of the standard as it can only be either of them? (see the `{Or` - `Or}` notation)
The examples show all possible (empty) fields. They don't represent the actual content well I guess?

There are other optional fields that the Nordeas app works without, right? If so, this sounds like a mistake on their end if they require both remittance fields?

**Comment by mstadius** [comment]
I think the problem is that there needs to be an empty line for the one that is not used so that the app can know which one is used and the value from `setInformation()` which has last position can be read correctly.
When i scanned the code with Nordeas app the content i set with `setInformation()` was shown as `AT-05 remittance information`. This also indicates that there needs to be correct number of lines.

Here are two links that show sample payload and they both have an empty line for the one that is not used:
- [finanssiala.fi](http://www.finanssiala.fi/maksujenvalitys/dokumentit/QR_koodin_kaytto_tilisiirtolomakkeella.pdf#page=6) Finnish language but you can see the sample payload
- [stuzza.at](https://www.stuzza.at/en/qr-code-generator.html) Generator that shows the payload

**Comment by smhg** [comment]
Thanks! I'll have a better look at it one of the next days. This should of course work as expected.

**Comment by smhg** [comment]
This is fixed and released as `2.2.0`. This part of the spec is now also correctly handled:
> The last populated element is not followed by any character or element separator.

Previously there were trailing newline characters.

Thank you for reporting this @mstadius!

**Comment by mstadius** [comment]
Great! Thank you for fixing it quickly!
