### ISSUE TITLE
Amount uses a comma, invalid code

### ISSUE THREAD

**Issue by CrazyHenk44** [smhg/sepa-qr-php#6]
Hi,

The barcode generated contains a comma in the amount 'EUR55,66'. This is because sprintf's f is locale aware. The comma is not acceptable. Please change it to a dot. Maybe [number_format](http://php.net/manual/en/function.number-format.php) is better in this case.

Best,

Tom

**Comment by smhg** [comment]
Good catch. Thanks!

Do you want to send a PR?

**Comment by CrazyHenk44** [comment]
I'm not familiar with that.

**Comment by smhg** [comment]
Fixed and released as `2.3.0`. Thanks @tomalbers!
