### ISSUE TITLE
Declaration of SepaQr\SepaQr::getWriter must be compatible...

### ISSUE THREAD

**Issue by benvanlooy** [smhg/sepa-qr-php#7]
First of all, thanks very much for creating SepaQR!

This is the error I'm getting though:

`Fatal error: Declaration of SepaQr\SepaQr::getWriter($name = NULL) must be compatible with Endroid\QrCode\QrCode::getWriter(?string $name = NULL): Endroid\QrCode\Writer\WriterInterface in ..SepaQr/SepaQr.php on line 11`

I do manage to create QR codes using: https://github.com/endroid/qr-code - but something goes wrong when I try to use SepaQR. Not sure what I'm doing wrong !

I'm not really sure how to adjust the functions without keeping on getting errors.

Can anyone help me please?

**Comment by smhg** [comment]
I assume you're using version 2.3.0 of this library:
Can you check your `composer.lock` file to see which version of `endroid/qr-code` you're using? It should be >=2, <3.

**Comment by benvanlooy** [comment]
Yes, that's correct!

```
 "name": "smhg/sepa-qr",
- "version": "v2.3.0",
```
and

```
 "name": "endroid/qr-code",
 "version": "2.5.1",
```

**Comment by benvanlooy** [comment]
Update: sorry you can remove this topic - I cleared all files & just started again and it seems to work now :-)

sorry for waisting your time!!

**Comment by smhg** [comment]
No problem! Thanks for the update!
